// <auto-generated />
using GrpcDemo.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GrpcDemo.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210401104054_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("GrpcDemo.Server.BookEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Book1"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Book2"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Book3"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Book4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
